services:
  api:
    image: amankhan1009/customer-support-agent-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      DATABASE_PATH: /data/support_checkpoints.db
    volumes:
      - support_data:/data

  frontend:
    image: amankhan1009/customer-support-agent-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api

volumes:
  support_data: